export const SET_WEAPON = "SET_NAME";
export const REMOVE_WEAPON = "REMOVE_WEAPON";
export const SET_ARMOR = "SET_ARMOR";
export const REMOVE_ARMOR = "REMOVE_ARMOR";

export const ADD_WEAPON_DURABILITY = "ADD_WEAPON_DURABILITY";
export const REDUCE_WEAPON_DURABILITY = "REDUCE_WEAPON_DURABILITY";
export const ADD_ARMOR_DURABILITY = "ADD_ARMOR_DURABILITY";
export const REDUCE_ARMOR_DURABILITY = "REDUCE_ARMOR_DURABILITY";
